#!/bin/bash

TYPE=RELEASE

BASE_DIR=/opt/vtk/source
INSTALL_DIR=/opt/vtk/install

cmake \
    -D CMAKE_BUILD_TYPE:STRING=$TYPE \
    -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
    -D BUILD_EXAMPLES:BOOL=OFF \
    -D BUILD_TESTING:BOOL=OFF \
    -D VTK_GROUP_ENABLE_Imaging=NO \
    -D VTK_GROUP_ENABLE_MPI=NO \
    -D VTK_GROUP_ENABLE_Qt=NO \
    -D VTK_GROUP_ENABLE_StandAlone=NO \
    -D VTK_GROUP_ENABLE_Views=NO \
    -D VTK_GROUP_ENABLE_Web=NO \
    -D VTK_MODULE_ENABLE_VTK_CommonCore=YES \
    -D VTK_MODULE_ENABLE_VTK_CommonExecutionModel=YES \
    -D VTK_MODULE_ENABLE_VTK_CommonMath=YES \
    -D VTK_MODULE_ENABLE_VTK_CommonMisc=YES \
    -D VTK_MODULE_ENABLE_VTK_CommonSystem=YES \
    -D VTK_MODULE_ENABLE_VTK_CommonTransforms=YES \
    -D VTK_MODULE_ENABLE_VTK_IOCore=YES \
    -D VTK_MODULE_ENABLE_VTK_IOLegacy=YES \
    -D VTK_MODULE_ENABLE_VTK_IOParallelXML=YES \
    -D VTK_MODULE_ENABLE_VTK_IOXML=YES \
    -D VTK_MODULE_ENABLE_VTK_IOXMLParser=YES \
    -D VTK_MODULE_ENABLE_VTK_ParallelCore=YES \
$BASE_DIR
